export const skills = [
    'Accounting',
    'Alertness',
    'Anthropology',
    'Archeology',
    'Art',
    'Artillery',
    'Athletics',
    'Bureaucracy',
    'Computer Science',
    'Craft',
    'Criminology',
    'Demolitions',
    'Disguise',
    'Dodge',
    'Drive',
    'Firearms',
    'First Aid',
    'Forensics',
    'Heavy Machinery',
    'Heavy Weapons',
    'History',
    'HUMINT',
    'Law',
    'Medicine',
    'Melee Weapons',
    'Military Science',
    'Navigate',
    'Occult',
    'Persuade',
    'Pharmacy',
    'Pilot',
    'Psychotherapy',
    'Ride',
    'Science',
    'Search',
    'SIGINT',
    'Stealth',
    'Surgery',
    'Survival',
    'Swim',
    'Unarmed Combat',
    'Unnatural',
];
