export const skillsSetup = {
    Alertness: 20,
    Anthropology: 0,
    Athletics: 20,
    Bureaucracy: 10,
    Communication: 10,
    Crafting: 0,
    'Criminal Activities': 10,
    Culture: 10,
    Disguise: 10,
    Dodge: 30,
    Drive: 20,
    'Human Insight': 10,
    Medicine: 0,
    Melee: 40,
    Navigation: 10,
    Occult: 10,
    Psych: 10,
    Ranged: 20,
    Science: 0,
    Stealth: 10,
    Survival: 10,
    Unnatural: 0,
};
